[package]
name = "kvarn-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3"
kvarn = { path = "../kvarn", default-features = false }
notify = "5.0.0-pre.13"
scraper = "^0.12"
elipdotter = { path = "../elipdotter" }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", default-features = false, features = ["sync"] }
walkdir = "^2"
